### ISSUE TITLE
xcLanguageSpecificationIdentifier can be quoted string

### ISSUE THREAD

**Issue by jomnius** [Karumi/Kin#17]
Got error note about this line:

> 527A67D41B8770CA00C4A690 /* LICENSE */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = text; lineEnding = 0; path = LICENSE; sourceTree = "<group>"; xcLanguageSpecificationIdentifier = "<none>"; };

We want to include LICENSE file into built application (for some reason I've forgotten) even if it is not a source code file. I believe this kin warning is not correct:

> ERROR: line 2038:204 mismatched input '"<none>"' expecting NON_QUOTED_STRING

**Comment by Serchinastico** [comment]
Hi @jomnius 

You are actually right, I'm including that case in Kin and release a new version.

Thanks for reporting!

**Comment by Serchinastico** [comment]
Version 1.5.0 fixes this issue
