### ISSUE TITLE
Build phase script error about input paths

### ISSUE THREAD

**Issue by jomnius** [Karumi/Kin#18]
Got this error note, not sure why. Looks ok to me, it also works during build:

> ERROR: line 4512:4 mismatched input '"$(SRCROOT)/Carthage/Build/iOS/Mantle.framework"' expecting {')', NON_QUOTED_STRING}

for this script input paths in build phase script (screenshot included):

```
/* Begin PBXShellScriptBuildPhase section */
		1A9BEBA51C7DD0C800FA3102 /* Carthage Run Script */ = {
			isa = PBXShellScriptBuildPhase;
			buildActionMask = 2147483647;
			files = (
			);
			inputPaths = (
				"$(SRCROOT)/Carthage/Build/iOS/Mantle.framework",
				"$(SRCROOT)/Carthage/Build/iOS/PromiseKit.framework",
				"$(SRCROOT)/Carthage/Build/iOS/OMGHTTPURLRQ.framework",
			);
			name = "Carthage Run Script";
			outputPaths = (
			);
			runOnlyForDeploymentPostprocessing = 0;
			shellPath = /bin/sh;
			shellScript = "/usr/local/bin/carthage copy-frameworks";
		};
```

![screen shot 2016-06-21 at 22 58 40](https://cloud.githubusercontent.com/assets/454519/16244238/c7017544-3803-11e6-8710-80c5b489a0b4.png)

**Comment by Serchinastico** [comment]
Hi!

Same as before, one of the many project configurations we didn't test.

Is your `project.pbxproj` publicly available? We'd love to add it as a test for Kin in order to verify this same error doesn't happen again in the future.

Thanks for reporting, I'm preparing a release now

**Comment by Serchinastico** [comment]
Version 1.5.0 fixes this issue
