### ISSUE TITLE
No module named 'verifier'

### ISSUE THREAD

**Issue by miranda-elliott** [Karumi/Kin#32]
When I try to run kin in my project directory it throws this error.

```
Traceback (most recent call last):
  File "//anaconda/bin/kin", line 7, in <module>
    from kin.kin import main
  File "//anaconda/lib/python3.5/site-packages/kin/kin.py", line 5, in <module>
    from verifier import Verifier
ImportError: No module named 'verifier'
```

I've tried to run` pip install verifier` but there's no matching distribution found for verifier. Please let me know which dependencies I need to install to make this run. Thank you!

**Comment by Serchinastico** [comment]
Hi @miranda-elliott 

Kin is configured with a `setup.py` file (https://docs.python.org/3/install/index.html) so you only need to run `python setup.py install` (keep in mind that it uses your default distutils settings so you might need admin permissions if you try to install it in a system directory). 

Besides, Kin was created with Python 2.7 so you need that version to run it. Let me know how does that work.

**Comment by thomasjoulin** [comment]
I had the same issue (I'm on macOS 10.13.3, python 2.7.10) after a `pip install kin`. I ended up cloning the repo and runing `python setup.py install` which works.
