### ISSUE TITLE
No module name 'verifier'

### ISSUE THREAD

**Issue by philosopherdog** [Karumi/Kin#35]
running kin produces this:
Traceback (most recent call last):
  File "/usr/local/bin/kin", line 6, in <module>
    from kin.kin import main
  File "/usr/local/lib/python3.6/site-packages/kin/kin.py", line 5, in <module>
    from verifier import Verifier
ModuleNotFoundError: No module named 'verifier'

**Comment by GregHilston** [comment]
This is because this project does not support python 3.

**Comment by Serchinastico** [comment]
@GregHilston is right, we don't support python 3 but we accept PRs adding support to it!

I'm closing the issue in the meantime.
