### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by ignacioespinoso** [Karumi/Kin#39]
I tried running Kin on a project and got this error

```bash
Traceback (most recent call last):
  File "/usr/local/bin/kin", line 5, in <module>
    from kin.kin import main
  File "/usr/local/lib/python3.7/site-packages/kin/kin.py", line 5, in <module>
    from verifier import Verifier
ModuleNotFoundError: No module named 'verifier'
```

**Comment by pedrovgs** [comment]
Hi @ignacioespinoso can you provide more information about how to reproduce the error? We'd also need to know what version of python you are using and the OS version. Loos like you are using python 3.7 but I'd like to double-check it.

**Comment by ignacioespinoso** [comment]
I simply installed using pip and then tried running in the project folder.
pip --version returns `pip 19.3.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)`
running python interpreter returns `Python 3.7.5 (default, Nov  1 2019, 02:16:23)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin`
I'm running on Catalina (10.15.4)

**Comment by pedrovgs** [comment]
Hi @ignacioespinoso I've found what's going on. You can find the same issue in #32. We had no time to update kin to use python3 so if you want to use kin, for now, you'll have to use python 2. I'm going to rename this issue to "Python 3 support".

**Comment by timwford** [comment]
Is there anything other than Python import stuff that needs to change for python 3 support? (read: what needs to happen to support python3?)

**Comment by Serchinastico** [comment]
We'd need to run ANTLR with the python3 target and migrate the CLI code ([see here](https://github.com/Karumi/Kin/tree/master/kin)) to python 3. Overall I don't think it's that hard but it'd take some time and I'm not sure I'd be able to find it in the near future. However, I think PRs are more than welcome to the project and I'd be glad to review them if that means we can get rid of python2 for good 😄
